### ISSUE TITLE
一个简单的例子

### ISSUE THREAD

**Issue by yu961549745** [xgdsmileboy/SubgraphIsomorphism#1]
目标是
v 0 1
v 1 2
v 2 3
e 0 1 1
e 0 2 2
查询
v 0 1
v 1 3
e 0 1 2
显然是子图，但是判断不是。

**Comment by xgdsmileboy** [comment]
e 0 1 1 和 e 0 1 2两条边的label是不一样的

**Comment by yu961549745** [comment]
不是按label匹配的吗，
(2)-1-(1)-2-(3)
         (1)-2-(3)
括号表示节点label，中间表示边的label，都有 (1)-2-(3)这条边。

**Comment by xgdsmileboy** [comment]
我检查了一下，缺失存在问题，原因在于我把Refine函数中的两个数组下标写反了，已经修复，你可以测试一下，多谢建议。

**Comment by yu961549745** [comment]
不客气，我才是来学习的。
